DELETE FROM `Egresados`.`T_CONTACTO` WHERE `ID_EMPRESA`='656';
DELETE FROM `Egresados`.`T_EMPRESA` WHERE `NIT`='656';
DELETE FROM `Egresados`.`T_CIUDAD` WHERE `ID_CIUDAD`='543';
DELETE FROM `Egresados`.`T_DEPARTAMENTO` WHERE `ID_DEPARTAMENTO`='432';
DELETE FROM `Egresados`.`T_PAIS` WHERE `cod`='321';
DELETE FROM `Egresados`.`T_SECTORLABORAL` WHERE `ID_SECTOR`='2';