DELETE FROM `Egresados`.`T_SECTORLABORAL` WHERE `ID_SECTOR`='432';
DELETE FROM `Egresados`.`T_PAIS` WHERE `cod`='567';
DELETE FROM `Egresados`.`T_DEPARTAMENTO` WHERE `ID_DEPARTAMENTO`='123';
DELETE FROM `Egresados`.`T_CIUDAD` WHERE `ID_CIUDAD`='345';