DELETE FROM `Egresados`.`T_INFO_ACADEMICA` WHERE `ID_EGRESADO`='123';
DELETE FROM `Egresados`.`T_EGRESADO` WHERE `ID_EGRESADO`='123';
DELETE FROM `Egresados`.`T_PROGRAMA` WHERE `ID_PROGRAMA`=12;
DELETE FROM `Egresados`.`T_FACULTAD` WHERE `ID_FACULTAD`=432;