DELETE FROM `Egresados`.`T_EMPRESA` WHERE `NIT`='1233';
DELETE FROM `Egresados`.`T_CIUDAD` WHERE `ID_CIUDAD`='345';
DELETE FROM `Egresados`.`T_DEPARTAMENTO` WHERE `ID_DEPARTAMENTO`='765';
DELETE FROM `Egresados`.`T_PAIS` WHERE `cod`='567'; 
DELETE FROM `Egresados`.`T_SECTORLABORAL` WHERE `ID_SECTOR`='43222';