DELETE FROM `Egresados`.`T_EMPRESA` WHERE `NIT`='654';
DELETE FROM `Egresados`.`T_SECTORLABORAL` WHERE `ID_SECTOR`='2';
DELETE FROM `Egresados`.`T_CIUDAD` WHERE `ID_CIUDAD`='543';
DELETE FROM `Egresados`.`T_DEPARTAMENTO` WHERE `ID_DEPARTAMENTO`='432';
DELETE FROM `Egresados`.`T_PAIS` WHERE `cod`='321';


