DELETE FROM `Egresados`.`T_INFO_LABORAL` WHERE `ID_EGRESADO`='123';
DELETE FROM `Egresados`.`T_EGRESADO` WHERE `ID_EGRESADO`='123';
DELETE FROM `Egresados`.`T_PROGRAMA` WHERE `ID_PROGRAMA`='456';
DELETE FROM `Egresados`.`T_FACULTAD` WHERE `ID_FACULTAD`='456789';
DELETE FROM `Egresados`.`T_SECTORLABORAL` WHERE `ID_SECTOR`='567';