/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.dinesoft.egresados.vista.gui;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import java.util.List;

import javax.swing.JOptionPane;

import co.edu.eam.dinesoft.egresados.vista.controladores.ControladorVentanaEgresados;
import co.edu.eam.ingesoftdesarrollo.egresados.persistencia.enumeraciones.NivelAcademico;
import co.edu.eam.ingesoftdesarrollo.egresados.persistencia.enumeraciones.SituacionActual;
import co.edu.eam.ingesoftdesarrollo.egresados.persistencia.enumeraciones.TipoEmpresa;
import co.edu.eam.ingesoftdesarrollo.egresados.persistencia.modelo.entidades.Egresado;
import co.edu.eam.ingesoftdesarrollo.egresados.persistencia.modelo.entidades.Empresa;
import co.edu.eam.ingesoftdesarrollo.egresados.persistencia.modelo.entidades.Facultad;
import co.edu.eam.ingesoftdesarrollo.egresados.persistencia.modelo.entidades.InfoAcademica;
import co.edu.eam.ingesoftdesarrollo.egresados.persistencia.modelo.entidades.InformacionLaboral;
import co.edu.eam.ingesoftdesarrollo.egresados.persistencia.modelo.entidades.Programa;
import co.edu.eam.ingesoftdesarrollo.egresados.persistencia.modelo.entidades.SectorLaboral;
import co.edu.eam.ingesoftdesarrollo.logica.excepcion.ExcepcionNegocio;

/**
 *
 * @author Didier Narv�ez
 */
public class VentanaEgresados extends javax.swing.JFrame implements ActionListener {

	private ControladorVentanaEgresados controlador;
	private Egresado egresadoEncontrado;

	/**
	 * Creates new form VentanaEgresados
	 */
	public VentanaEgresados() {
		controlador = new ControladorVentanaEgresados();
		egresadoEncontrado = null;
		initComponents();
		setLocationRelativeTo(this);
		jBAnterior.setVisible(false);
		jTPPestanias.setEnabledAt(2, false);
		jTPPestanias.setEnabledAt(1, false);
		jBCancelar.addActionListener(this);
		jBAgregarInfo.addActionListener(this);
		jBBuscar.addActionListener(this);
		jBEditar.addActionListener(this);
		jBInicio.addActionListener(this);
		jBRegistro.addActionListener(this);
		jBSiguiente.addActionListener(this);
		jBAnterior.addActionListener(this);
		jpColor jpVista = new jpColor();
		jpVista.setSize(this.getSize());
		jBRegistro.setVisible(false);
		pintarPanelPrincipal();
		refrescarComboSituacionActual();
		refrescarComboSectorLab();
		refrescarComboNivelAcademico();
		refresacarComboEmpresas();
		refrescarComboTipoEmpresa();
		refrescarComboFacultad();
		pintarPanelRegistro();
		jBAgregarInfo.setVisible(false);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jTextField5 = new javax.swing.JTextField();
		jPPrinci = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jTPPestanias = new javax.swing.JTabbedPane();
		jPInfoPer = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jTFNombres = new javax.swing.JTextField();
		jTFCorreo = new javax.swing.JTextField();
		jTFApellidos = new javax.swing.JTextField();
		jTFId = new javax.swing.JTextField();
		jTFTel = new javax.swing.JTextField();
		jCBTipoDoc = new javax.swing.JComboBox();
		jLabel22 = new javax.swing.JLabel();
		jTFCodigoEgresado = new javax.swing.JTextField();
		jPInfoAcademica = new javax.swing.JPanel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jTFNumeroDiploma = new javax.swing.JTextField();
		jCBPrograma = new javax.swing.JComboBox();
		jDFechaGrado = new com.toedter.calendar.JDateChooser();
		jLabel20 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTAAreasLaborales = new javax.swing.JTextArea();
		comboFacultad = new javax.swing.JComboBox();
		jCBNivel = new javax.swing.JComboBox();
		jPInfoLaboral = new javax.swing.JPanel();
		jLabel13 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();
		jLabel16 = new javax.swing.JLabel();
		jLabel17 = new javax.swing.JLabel();
		jLabel18 = new javax.swing.JLabel();
		jLabel19 = new javax.swing.JLabel();
		jBAgregarInfo = new javax.swing.JButton();
		jDFechaIngreso = new com.toedter.calendar.JDateChooser();
		jDFechaSalida = new com.toedter.calendar.JDateChooser();
		jTFCargo = new javax.swing.JTextField();
		jCBSituacionActual = new javax.swing.JComboBox();
		jCBTipoEmp = new javax.swing.JComboBox();
		jCBSectorLab = new javax.swing.JComboBox();
		jCBEmpresaEgre = new javax.swing.JComboBox();
		jBSiguiente = new javax.swing.JButton();
		jBCancelar = new javax.swing.JButton();
		jPOpciones = new javax.swing.JPanel();
		jBRegistro = new javax.swing.JButton();
		jBBuscar = new javax.swing.JButton();
		jBEditar = new javax.swing.JButton();
		jBInicio = new javax.swing.JButton();
		jBAnterior = new javax.swing.JButton();
		jLabel21 = new javax.swing.JLabel();

		jTextField5.setText("jTextField5");

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Bernard MT Condensed", 0, 36)); // NOI18N
		jLabel1.setText("REGISTRO DE EGRESADOS");

		jTPPestanias.setFont(new java.awt.Font("Bernard MT Condensed", 0, 12)); // NOI18N

		jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabel2.setText("Nombres");

		jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabel3.setText("Apellidos");

		jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabel4.setText("Tipo de documento");

		jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabel5.setText("N�mero de documento");

		jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabel6.setText("Correo electr�nico");

		jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabel7.setText("N�mero telef�nico");

		jCBTipoDoc.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jCBTipoDoc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opci�n",
				"Tarjeta de identidad", "C�dula de ciudadania", "C�dula de extranjer�a" }));

		jLabel22.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabel22.setText("C�digo");

		javax.swing.GroupLayout jPInfoPerLayout = new javax.swing.GroupLayout(jPInfoPer);
		jPInfoPer.setLayout(jPInfoPerLayout);
		jPInfoPerLayout.setHorizontalGroup(jPInfoPerLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPInfoPerLayout.createSequentialGroup().addGap(38, 38, 38).addGroup(jPInfoPerLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel5)
						.addComponent(jTFId, javax.swing.GroupLayout.PREFERRED_SIZE, 213,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGroup(jPInfoPerLayout.createSequentialGroup()
								.addGroup(jPInfoPerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel2)
										.addComponent(jTFNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 213,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel3)
										.addComponent(jTFApellidos, javax.swing.GroupLayout.PREFERRED_SIZE,
												213, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel4).addComponent(jCBTipoDoc,
												javax.swing.GroupLayout.PREFERRED_SIZE, 213,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(65, 65,
										65)
								.addGroup(jPInfoPerLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(jLabel22)
										.addComponent(jTFTel, javax.swing.GroupLayout.DEFAULT_SIZE, 204,
												Short.MAX_VALUE)
										.addComponent(jTFCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 204,
												Short.MAX_VALUE)
										.addComponent(jLabel6).addComponent(jLabel7).addComponent(jTFCodigoEgresado))))
						.addGap(10, 10, 10)));
		jPInfoPerLayout.setVerticalGroup(jPInfoPerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPInfoPerLayout.createSequentialGroup()
						.addGroup(jPInfoPerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPInfoPerLayout.createSequentialGroup().addGap(38, 38, 38)
										.addComponent(jLabel2).addGap(6, 6, 6))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPInfoPerLayout.createSequentialGroup().addContainerGap().addComponent(jLabel6)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
						.addGroup(jPInfoPerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jTFNombres, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jTFCorreo, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(11, 11, 11)
						.addGroup(jPInfoPerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3).addComponent(jLabel7))
						.addGap(6, 6, 6)
						.addGroup(jPInfoPerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jTFApellidos, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jTFTel, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPInfoPerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel4).addComponent(jLabel22))
						.addGap(22, 22, 22)
						.addGroup(jPInfoPerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jCBTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jTFCodigoEgresado, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18).addComponent(jLabel5).addGap(18, 18, 18).addComponent(jTFId,
								javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)));

		jTPPestanias.addTab("1.INFORMACI�N PERSONAL", jPInfoPer);

		jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabel8.setText("Facultad");

		jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabel9.setText("Programa acad�mico");

		jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabel10.setText("Feha de grado");

		jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabel11.setText("Nivel acad�mico");

		jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabel12.setText("N�mero del diploma");

		jCBPrograma.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

		jLabel20.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabel20.setText("Areas de oferta laboral");

		jTAAreasLaborales.setColumns(20);
		jTAAreasLaborales.setRows(5);
		jScrollPane1.setViewportView(jTAAreasLaborales);

		comboFacultad.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				comboFacultadItemStateChanged(evt);
			}
		});

		javax.swing.GroupLayout jPInfoAcademicaLayout = new javax.swing.GroupLayout(jPInfoAcademica);
		jPInfoAcademica.setLayout(jPInfoAcademicaLayout);
		jPInfoAcademicaLayout
				.setHorizontalGroup(
						jPInfoAcademicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(
										jPInfoAcademicaLayout.createSequentialGroup().addGap(23, 23, 23)
												.addGroup(jPInfoAcademicaLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(jLabel11).addComponent(jLabel8)
														.addComponent(jLabel10)
														.addComponent(jDFechaGrado,
																javax.swing.GroupLayout.DEFAULT_SIZE, 200,
																Short.MAX_VALUE)
														.addComponent(comboFacultad, 0,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jCBNivel, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
												.addGap(49, 49, 49)
												.addGroup(
														jPInfoAcademicaLayout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jLabel20)
																.addComponent(jScrollPane1,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 256,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jLabel12)
																.addComponent(
																		jTFNumeroDiploma,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 214,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGroup(
																		jPInfoAcademicaLayout
																				.createParallelGroup(
																						javax.swing.GroupLayout.Alignment.LEADING,
																						false)
																				.addComponent(jLabel9)
																				.addComponent(jCBPrograma, 0, 200,
																						Short.MAX_VALUE)))
												.addContainerGap(35, Short.MAX_VALUE)));
		jPInfoAcademicaLayout.setVerticalGroup(jPInfoAcademicaLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPInfoAcademicaLayout.createSequentialGroup().addContainerGap(42, Short.MAX_VALUE)
						.addGroup(jPInfoAcademicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel9).addComponent(jLabel8))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPInfoAcademicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jCBPrograma, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(comboFacultad, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(
								jPInfoAcademicaLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addGroup(jPInfoAcademicaLayout.createSequentialGroup().addComponent(jLabel10)
												.addGap(18, 18, 18)
												.addComponent(jDFechaGrado, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(jPInfoAcademicaLayout.createSequentialGroup().addComponent(jLabel12)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jTFNumeroDiploma, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18).addComponent(jLabel20)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPInfoAcademicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPInfoAcademicaLayout.createSequentialGroup().addComponent(jLabel11)
												.addGap(18, 18, 18)
												.addComponent(jCBNivel, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(14, 14, 14)))
						.addContainerGap(28, Short.MAX_VALUE)));

		jTPPestanias.addTab("2.INFORMACI�N ACAD�MICA", jPInfoAcademica);

		jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabel13.setText("Sitiaci�n actual");

		jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabel14.setText("Tipo de empresa");

		jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabel15.setText("Sector laboral");

		jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabel16.setText("Empresa");

		jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabel17.setText("Fecha de ingreso");

		jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabel18.setText("Fecha de salida");

		jLabel19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabel19.setText("Cargo en la empresa");

		jBAgregarInfo.setBackground(new java.awt.Color(255, 255, 255));
		jBAgregarInfo.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
		jBAgregarInfo.setForeground(new java.awt.Color(0, 0, 153));
		jBAgregarInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1471496893_tick_green.png"))); // NOI18N
		jBAgregarInfo.setText("AGREGAR INFORMACION LABORAL");

		jCBSituacionActual.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jCBSituacionActual.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				jCBSituacionActualItemStateChanged(evt);
			}
		});

		jCBTipoEmp.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

		javax.swing.GroupLayout jPInfoLaboralLayout = new javax.swing.GroupLayout(jPInfoLaboral);
		jPInfoLaboral.setLayout(jPInfoLaboralLayout);
		jPInfoLaboralLayout.setHorizontalGroup(jPInfoLaboralLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPInfoLaboralLayout.createSequentialGroup().addGap(26, 26, 26).addGroup(
						jPInfoLaboralLayout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPInfoLaboralLayout
										.createSequentialGroup().addGroup(jPInfoLaboralLayout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPInfoLaboralLayout
														.createSequentialGroup().addGroup(jPInfoLaboralLayout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jLabel13).addComponent(jLabel14)
																.addComponent(jLabel15))
														.addGap(194, 194, 194)
														.addGroup(jPInfoLaboralLayout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jLabel19).addComponent(jLabel18)
																.addComponent(jLabel17)))
												.addGroup(jPInfoLaboralLayout.createSequentialGroup()
														.addGroup(jPInfoLaboralLayout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING,
																		false)
																.addComponent(jCBSituacionActual,
																		javax.swing.GroupLayout.Alignment.TRAILING, 0,
																		201, Short.MAX_VALUE)
																.addComponent(jCBTipoEmp,
																		javax.swing.GroupLayout.Alignment.TRAILING, 0,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(jCBSectorLab, 0,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE))
														.addGap(72, 72, 72)
														.addGroup(jPInfoLaboralLayout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING,
																		false)
																.addComponent(jDFechaIngreso,
																		javax.swing.GroupLayout.DEFAULT_SIZE, 198,
																		Short.MAX_VALUE)
																.addComponent(jDFechaSalida,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(jTFCargo))))
										.addContainerGap(66, Short.MAX_VALUE))
								.addGroup(jPInfoLaboralLayout.createSequentialGroup()
										.addGroup(jPInfoLaboralLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel16)
												.addComponent(jCBEmpresaEgre, javax.swing.GroupLayout.PREFERRED_SIZE,
														201, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45,
												Short.MAX_VALUE)
										.addComponent(jBAgregarInfo).addGap(26, 26, 26)))));
		jPInfoLaboralLayout.setVerticalGroup(jPInfoLaboralLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPInfoLaboralLayout.createSequentialGroup().addGap(37, 37, 37)
						.addGroup(jPInfoLaboralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel13).addComponent(jLabel17))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPInfoLaboralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jDFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jCBSituacionActual, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(19, 19, 19)
						.addGroup(jPInfoLaboralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel14).addComponent(jLabel18))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPInfoLaboralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jDFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jCBTipoEmp, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(jPInfoLaboralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPInfoLaboralLayout.createSequentialGroup().addGap(22, 22, 22)
										.addComponent(jLabel19))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPInfoLaboralLayout.createSequentialGroup()
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jLabel15)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPInfoLaboralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jTFCargo, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jCBSectorLab, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(jPInfoLaboralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPInfoLaboralLayout.createSequentialGroup().addGap(13, 13, 13)
										.addComponent(jLabel16).addGap(18, 18, 18).addComponent(jCBEmpresaEgre,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPInfoLaboralLayout.createSequentialGroup().addGap(18, 18, 18).addComponent(
										jBAgregarInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 61,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(24, Short.MAX_VALUE)));

		jTPPestanias.addTab("3.INFORMACI�N LABORAL", jPInfoLaboral);

		jBSiguiente.setBackground(new java.awt.Color(255, 255, 255));
		jBSiguiente.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
		jBSiguiente.setForeground(new java.awt.Color(0, 0, 153));
		jBSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1471495851_go-next_1.png"))); // NOI18N
		jBSiguiente.setText("SIGUIENTE");

		jBCancelar.setBackground(new java.awt.Color(255, 255, 255));
		jBCancelar.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
		jBCancelar.setForeground(new java.awt.Color(0, 0, 153));
		jBCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1471496222_button_cancel.png"))); // NOI18N
		jBCancelar.setText("CANCELAR");

		jPOpciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Bernard MT Condensed", 0, 14))); // NOI18N

		jBRegistro.setBackground(new java.awt.Color(255, 255, 255));
		jBRegistro.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
		jBRegistro.setForeground(new java.awt.Color(0, 0, 153));
		jBRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1471496828_Add-Male-User.png"))); // NOI18N
		jBRegistro.setText("REGISTRAR");

		jBBuscar.setBackground(new java.awt.Color(255, 255, 255));
		jBBuscar.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
		jBBuscar.setForeground(new java.awt.Color(0, 0, 153));
		jBBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1471496705_search.png"))); // NOI18N
		jBBuscar.setText("BUSCAR");

		jBEditar.setBackground(new java.awt.Color(255, 255, 255));
		jBEditar.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
		jBEditar.setForeground(new java.awt.Color(0, 0, 153));
		jBEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1471496619_interact.png"))); // NOI18N
		jBEditar.setText("EDITAR");

		javax.swing.GroupLayout jPOpcionesLayout = new javax.swing.GroupLayout(jPOpciones);
		jPOpciones.setLayout(jPOpcionesLayout);
		jPOpcionesLayout
				.setHorizontalGroup(jPOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								jPOpcionesLayout.createSequentialGroup().addGap(0, 27, Short.MAX_VALUE)
										.addGroup(jPOpcionesLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
												.addComponent(jBEditar, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jBBuscar, javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jBRegistro, javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addGap(19, 19, 19)));
		jPOpcionesLayout
				.setVerticalGroup(jPOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPOpcionesLayout.createSequentialGroup().addGap(28, 28, 28).addComponent(jBRegistro)
								.addGap(28, 28, 28).addComponent(jBBuscar)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31,
										Short.MAX_VALUE)
								.addComponent(jBEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 71,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap()));

		jBInicio.setBackground(new java.awt.Color(255, 255, 255));
		jBInicio.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
		jBInicio.setForeground(new java.awt.Color(0, 0, 153));
		jBInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1471496349_home.png"))); // NOI18N
		jBInicio.setText("INICIO");

		jBAnterior.setBackground(new java.awt.Color(255, 255, 255));
		jBAnterior.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
		jBAnterior.setForeground(new java.awt.Color(0, 0, 153));
		jBAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1471496101_Undo.png"))); // NOI18N
		jBAnterior.setText("ANTERIOR");

		jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1471495526_graduated.png"))); // NOI18N

		javax.swing.GroupLayout jPPrinciLayout = new javax.swing.GroupLayout(jPPrinci);
		jPPrinci.setLayout(jPPrinciLayout);
		jPPrinciLayout.setHorizontalGroup(jPPrinciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPPrinciLayout
						.createSequentialGroup().addGroup(
								jPPrinciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPPrinciLayout.createSequentialGroup().addGap(183, 183, 183)
												.addComponent(jLabel1).addGap(50, 50, 50).addComponent(jLabel21))
										.addGroup(jPPrinciLayout.createSequentialGroup().addGap(16, 16, 16)
												.addComponent(jTPPestanias, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(12, 12, 12).addComponent(jPOpciones,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(12, Short.MAX_VALUE))
				.addGroup(jPPrinciLayout.createSequentialGroup().addGap(30, 30, 30).addComponent(jBCancelar)
						.addGap(49, 49, 49).addComponent(jBAnterior).addGap(51, 51, 51).addComponent(jBSiguiente)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jBInicio).addGap(43, 43, 43)));
		jPPrinciLayout.setVerticalGroup(jPPrinciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPPrinciLayout.createSequentialGroup().addGap(11, 11, 11).addGroup(jPPrinciLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPPrinciLayout.createSequentialGroup().addGap(48, 48, 48).addComponent(jLabel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addComponent(jLabel21))
						.addGap(11, 11, 11)
						.addGroup(jPPrinciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jTPPestanias, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(jPPrinciLayout.createSequentialGroup().addGap(20, 20, 20).addComponent(
										jPOpciones, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(jPPrinciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPPrinciLayout.createSequentialGroup().addGap(15, 15, 15)
										.addGroup(jPPrinciLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 69,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jBAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 69,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jBSiguiente)))
								.addGroup(jPPrinciLayout.createSequentialGroup()
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jBInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 71,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPPrinci, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPPrinci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jCBSituacionActualItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_jCBSituacionActualItemStateChanged
		// TODO add your handling code here:
		if (jCBSituacionActual.getSelectedIndex() != 0) {
			int index = jCBSituacionActual.getSelectedIndex();
			if (index == 1 || index == 4) {
				jCBTipoEmp.setEnabled(false);
				jCBSectorLab.setEnabled(false);
				jCBEmpresaEgre.setEnabled(false);
				jDFechaIngreso.setEnabled(false);
				jDFechaSalida.setEnabled(false);
				jTFCargo.setEditable(false);
			} else {
				jCBTipoEmp.setEnabled(true);
				jCBSectorLab.setEnabled(true);
				jCBEmpresaEgre.setEnabled(true);
				jDFechaIngreso.setEnabled(true);
				jDFechaSalida.setEnabled(true);
				jTFCargo.setEditable(true);
			}
		}
	}// GEN-LAST:event_jCBSituacionActualItemStateChanged

	private void comboFacultadItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_comboFacultadItemStateChanged
		// TODO add your handling code here:
		if (comboFacultad.getSelectedIndex() != 0) {
			Facultad f = (Facultad) comboFacultad.getSelectedItem();
			refrescarComboPrograma(f);
		}
	}// GEN-LAST:event_comboFacultadItemStateChanged

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JComboBox comboFacultad;
	private javax.swing.JButton jBAgregarInfo;
	private javax.swing.JButton jBAnterior;
	private javax.swing.JButton jBBuscar;
	private javax.swing.JButton jBCancelar;
	private javax.swing.JButton jBEditar;
	private javax.swing.JButton jBInicio;
	private javax.swing.JButton jBRegistro;
	private javax.swing.JButton jBSiguiente;
	private javax.swing.JComboBox jCBEmpresaEgre;
	private javax.swing.JComboBox jCBNivel;
	private javax.swing.JComboBox jCBPrograma;
	private javax.swing.JComboBox jCBSectorLab;
	private javax.swing.JComboBox jCBSituacionActual;
	private javax.swing.JComboBox jCBTipoDoc;
	private javax.swing.JComboBox jCBTipoEmp;
	private com.toedter.calendar.JDateChooser jDFechaGrado;
	private com.toedter.calendar.JDateChooser jDFechaIngreso;
	private com.toedter.calendar.JDateChooser jDFechaSalida;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel22;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPInfoAcademica;
	private javax.swing.JPanel jPInfoLaboral;
	private javax.swing.JPanel jPInfoPer;
	private javax.swing.JPanel jPOpciones;
	private javax.swing.JPanel jPPrinci;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTAAreasLaborales;
	private javax.swing.JTextField jTFApellidos;
	private javax.swing.JTextField jTFCargo;
	private javax.swing.JTextField jTFCodigoEgresado;
	private javax.swing.JTextField jTFCorreo;
	private javax.swing.JTextField jTFId;
	private javax.swing.JTextField jTFNombres;
	private javax.swing.JTextField jTFNumeroDiploma;
	private javax.swing.JTextField jTFTel;
	private javax.swing.JTabbedPane jTPPestanias;
	private javax.swing.JTextField jTextField5;

	// End of variables declaration//GEN-END:variables
	public void actionPerformed(ActionEvent arg0) {

		if (arg0.getSource() == jBAgregarInfo) {

		}

		if (arg0.getSource() == jBBuscar) {

			try {
				String id = JOptionPane.showInputDialog(null, "Ingrese n�mero de identificaci�n del egresado");
				Egresado e = controlador.buscar(id);
				egresadoEncontrado = e;

				// LLenando datos personales
				jTFNombres.setText(e.getNombre());
				jTFApellidos.setText(e.getApellido());
				jCBTipoDoc.setSelectedItem(e.getTipoDocumento());
				jTFId.setText(e.getNumDocumento());
				jTFCorreo.setText(e.getCorreo());
				jTFTel.setText(e.getNumTel());
				jTFCodigoEgresado.setText(e.getCodigoEgresado() + "");

				// Llenando datos de informaci�n acad�mica
				InfoAcademica info = controlador.buscarInfoAcademica(e);

				comboFacultad.setSelectedItem(info.getFacultad());
				jDFechaGrado.setDate(info.getFechaGrado());
				jCBNivel.setSelectedItem(info.getNivelAcademico());
				jCBPrograma.setSelectedItem(info.getProgramaAcademico());
				jTFNumeroDiploma.setText(info.getNumDiploma());
				jTAAreasLaborales.setText(info.getAreaOfertaLaboral());

				// Llenando datos informaci�n laboral
				InformacionLaboral infoLab = controlador.buscarInfoLab(e);

				if (infoLab.getSituaActual().equals(SituacionActual.DESEMPLEADO)
						|| infoLab.getSituaActual().equals(SituacionActual.INDEPENDIENTE)) {
					jCBTipoEmp.setSelectedIndex(0);
					jCBSectorLab.setSelectedIndex(0);
					jCBEmpresaEgre.setSelectedIndex(0);
					jDFechaIngreso.setDate(null);
					jDFechaSalida.setDate(null);
					jTFCargo.setText(null);
				} else {
					jCBSituacionActual.setSelectedItem(infoLab.getSituaActual());
					jCBTipoEmp.setSelectedItem(infoLab.getTipoEmpresa());
					jCBSectorLab.setSelectedItem(infoLab.getSectorLaboral());
					jCBEmpresaEgre.setSelectedItem(infoLab.getEmpresa());
					jDFechaIngreso.setDate(infoLab.getFechaIngreso());
					jDFechaSalida.setDate(infoLab.getFechaSalida());
					jTFCargo.setText(infoLab.getCargo());
				}

			} catch (ExcepcionNegocio e) {
				JOptionPane.showMessageDialog(null, e.getMessage());
			} catch (Exception exc) {
				exc.printStackTrace();
			}

		}

		if (arg0.getSource() == jBCancelar) {

			int opc = JOptionPane.showConfirmDialog(null, "Esta seguro que desea cancelar");
			if (opc == 0) {
				LimpiarCampos();
				jTPPestanias.setSelectedIndex(0);
 			}

		}

		if (arg0.getSource() == jBEditar) {

			try {

				if (egresadoEncontrado == null) {
					JOptionPane.showMessageDialog(null, "Debe buscar antes de editar");
				} else {
					// Datos personales egresado
					String nombre = jTFNombres.getText();
					String ape = jTFApellidos.getText();
					String tipoDoc = (String) jCBTipoDoc.getSelectedItem();
					String id = jTFId.getText();
					String correo = jTFCorreo.getText();
					String tel = jTFTel.getText();
					String cod = jTFCodigoEgresado.getText();

					// Informaci�n acad�mica
					Facultad facultad = (Facultad) comboFacultad.getSelectedItem();
					Date fechaGrado = jDFechaGrado.getDate();
					NivelAcademico nivel = (NivelAcademico) jCBNivel.getSelectedItem();
					Programa programa = (Programa) jCBPrograma.getSelectedItem();
					String numDiploma = jTFNumeroDiploma.getText();
					String areasOferta = jTAAreasLaborales.getText();

					// Informaci�n laboral
					SituacionActual situa = (SituacionActual) jCBSituacionActual.getSelectedItem();

					// Crear egresado
					Egresado e = new Egresado(cod, programa, nombre, ape, tipoDoc, id, correo, tel);

					// agregar Informaci�n laboral

					InformacionLaboral infoLab = controlador.buscarInfoLab(egresadoEncontrado);

					if (situa.equals(SituacionActual.DESEMPLEADO) || situa.equals(SituacionActual.INDEPENDIENTE)) {
						infoLab.setEgresado(e);
						infoLab.setSituaActual(situa);
					} else {
						TipoEmpresa tipoEmp = (TipoEmpresa) jCBTipoEmp.getSelectedItem();
						SectorLaboral sectorLab = (SectorLaboral) jCBSectorLab.getSelectedItem();

						Empresa nomEmp = (Empresa) jCBEmpresaEgre.getSelectedItem();
						Date fechaIngreso = jDFechaIngreso.getDate();
						Date fechaSalida = jDFechaSalida.getDate();
						String cargo = jTFCargo.getText();

						infoLab.setEgresado(egresadoEncontrado);
						infoLab.setTipoEmpresa(tipoEmp);
						infoLab.setSectorLaboral(sectorLab);
						infoLab.setEmpresa(nomEmp);
						infoLab.setFechaIngreso(fechaIngreso);
						infoLab.setFechaSalida(fechaSalida);
						infoLab.setCargo(cargo);
						infoLab.setSituaActual(situa);
					}

					// Agregar informaci�n acad�mica
					InfoAcademica info = new InfoAcademica(e, fechaGrado, facultad, nivel, programa, numDiploma,
							areasOferta);

					controlador.actualizar(e, info, infoLab);
					JOptionPane.showMessageDialog(null, "Se ha actualizado la informaci�n correctamente");

						controlador.actualizar(e, info, infoLab);
						JOptionPane.showMessageDialog(null, "Se ha actualizado la informaci�n correctamente");
						LimpiarCampos();
					}
				
			} catch (Exception e) {
				e.printStackTrace();
			}
		}


		if (arg0.getSource() == jBInicio) {
			this.dispose();
		}

		if (arg0.getSource() == jBRegistro) {

			try {

				// Datos personales egresado
				String nombre = jTFNombres.getText();
				String ape = jTFApellidos.getText();
				String tipoDoc = (String) jCBTipoDoc.getSelectedItem();
				String id = jTFId.getText();
				String correo = jTFCorreo.getText();
				String tel = jTFTel.getText();
				String cod = jTFCodigoEgresado.getText();

				// Informaci�n acad�mica
				Facultad facultad = (Facultad) comboFacultad.getSelectedItem();
				Date fechaGrado = jDFechaGrado.getDate();
				NivelAcademico nivel = (NivelAcademico) jCBNivel.getSelectedItem();
				Programa programa = (Programa) jCBPrograma.getSelectedItem();
				String numDiploma = jTFNumeroDiploma.getText();
				String areasOferta = jTAAreasLaborales.getText();

				// Informaci�n laboral
				SituacionActual situa = (SituacionActual) jCBSituacionActual.getSelectedItem();

				// Crear egresado
				Egresado e = new Egresado(cod, programa, nombre, ape, tipoDoc, id, correo, tel);

				// agregar Informaci�n laboral
				InformacionLaboral infoLab = new InformacionLaboral();

				if (situa.equals(SituacionActual.DESEMPLEADO) || situa.equals(SituacionActual.INDEPENDIENTE)) {
					infoLab.setEgresado(e);
					infoLab.setSituaActual(situa);
				} else {
					TipoEmpresa tipoEmp = (TipoEmpresa) jCBTipoEmp.getSelectedItem();
					SectorLaboral sectorLab = (SectorLaboral) jCBSectorLab.getSelectedItem();

					Empresa nomEmp = (Empresa) jCBEmpresaEgre.getSelectedItem();
					Date fechaIngreso = jDFechaIngreso.getDate();
					Date fechaSalida = jDFechaSalida.getDate();
					String cargo = jTFCargo.getText();

					infoLab.setEgresado(e);
					infoLab.setTipoEmpresa(tipoEmp);
					infoLab.setSectorLaboral(sectorLab);
					infoLab.setEmpresa(nomEmp);
					infoLab.setFechaIngreso(fechaIngreso);
					infoLab.setFechaSalida(fechaSalida);
					infoLab.setCargo(cargo);
				}

				// Agregar informaci�n acad�mica
				InfoAcademica info = new InfoAcademica(e, fechaGrado, facultad, nivel, programa, numDiploma,
						areasOferta);

					controlador.registrar(e, info, infoLab);
					JOptionPane.showMessageDialog(null, "La informaci�n se ha agregado satisfactoriamente");
					LimpiarCampos();

			} catch (ExcepcionNegocio e) {
				JOptionPane.showMessageDialog(null, e.getMessage());
			} catch (Exception exc) {
				exc.printStackTrace();
			}

		}

		if (arg0.getSource() == jBSiguiente) {

			if (jTPPestanias.getSelectedIndex() == 0) {
				jBAnterior.setVisible(true);
				jTPPestanias.setEnabledAt(1, true);
				jTPPestanias.setSelectedIndex(1);
				jTPPestanias.setEnabledAt(0, false);

			} else if (jTPPestanias.getSelectedIndex() == 1) {
				jBAnterior.setVisible(true);
				jTPPestanias.setEnabledAt(2, true);
				jTPPestanias.setSelectedIndex(2);
				jTPPestanias.setEnabledAt(1, false);
				jBSiguiente.setVisible(false);
				jBRegistro.setVisible(true);

			}

		}

		if (arg0.getSource() == jBAnterior) {

			if (jTPPestanias.getSelectedIndex() == 1) {
				jTPPestanias.setEnabledAt(0, true);
				jTPPestanias.setSelectedIndex(0);
				jTPPestanias.setEnabledAt(1, false);
				jBAnterior.setVisible(false);

			} else if (jTPPestanias.getSelectedIndex() == 2) {
				jBSiguiente.setVisible(true);
				jBRegistro.setVisible(false);
				jTPPestanias.setEnabledAt(1, true);
				jTPPestanias.setSelectedIndex(1);
				jTPPestanias.setEnabledAt(2, false);
			}
		}
	}

	private void refrescarComboFacultad() {
		try {
			List<Facultad> lista = controlador.listaFacultades();
			comboFacultad.removeAllItems();
			comboFacultad.addItem("Seleccione opci�n");
			for (Facultad facultad : lista) {
				comboFacultad.addItem(facultad);
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private void refrescarComboPrograma(Facultad f) {
		try {

			List<Programa> lista = controlador.programasFacultad(f);
			jCBPrograma.removeAllItems();
			jCBPrograma.addItem("Seleccione opci�n");
			for (Programa programa : lista) {
				jCBPrograma.addItem(programa);
			}

		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void LimpiarCampos() {
		if(comboFacultad.getSelectedIndex() > 0){
			jTFNombres.setText(null);
			jTFApellidos.setText(null);
			jCBTipoDoc.setSelectedIndex(0);
			jTFId.setText(null);
			jTFCorreo.setText(null);
			jTFTel.setText(null);
			jTFCodigoEgresado.setText(null);
			comboFacultad.setSelectedIndex(0);
			jDFechaGrado.setDate(null);
			jCBNivel.setSelectedIndex(0);
			jCBPrograma.setSelectedIndex(0);
			jTFNumeroDiploma.setText(null);
			jTAAreasLaborales.setText(null);
			jCBSituacionActual.setSelectedIndex(0);
			jCBTipoEmp.setSelectedIndex(0);
			jCBSectorLab.setSelectedIndex(0);
			jCBEmpresaEgre.setSelectedIndex(0);
			jDFechaIngreso.setDate(null);
			jDFechaSalida.setDate(null);
			jTFCargo.setText(null);
			jTPPestanias.setSelectedIndex(0);
			
		}else{
			jTFNombres.setText(null);
			jTFApellidos.setText(null);
			jCBTipoDoc.setSelectedIndex(0);
			jTFId.setText(null);
			jTFCorreo.setText(null);
			jTFTel.setText(null);
			jTFCodigoEgresado.setText(null);
			comboFacultad.setSelectedIndex(0);
			jDFechaGrado.setDate(null);
			jCBNivel.setSelectedIndex(0);
			jTFNumeroDiploma.setText(null);
			jTAAreasLaborales.setText(null);
			jCBSituacionActual.setSelectedIndex(0);
			jCBTipoEmp.setSelectedIndex(0);
			jCBSectorLab.setSelectedIndex(0);
			jCBEmpresaEgre.setSelectedIndex(0);
			jDFechaIngreso.setDate(null);
			jDFechaSalida.setDate(null);
			jTFCargo.setText(null);
			jTPPestanias.setSelectedIndex(0);
		}
		
	}

	private void refrescarComboSituacionActual() {
		jCBSituacionActual.addItem("Seleccione una opci�n");
		jCBSituacionActual.addItem(SituacionActual.DESEMPLEADO);
		jCBSituacionActual.addItem(SituacionActual.EMPLEADO);
		jCBSituacionActual.addItem(SituacionActual.EMPRESARIO);
		jCBSituacionActual.addItem(SituacionActual.INDEPENDIENTE);
	}

	private void refrescarComboNivelAcademico() {
		jCBNivel.addItem("Seleccione una opci�n");
		jCBNivel.addItem(NivelAcademico.DIPLOMADO);
		jCBNivel.addItem(NivelAcademico.POSTGRADO);
		jCBNivel.addItem(NivelAcademico.PREGRADO);
	}

	private void refrescarComboTipoEmpresa() {
		jCBTipoEmp.addItem("Seleccione una opci�n");
		jCBTipoEmp.addItem(TipoEmpresa.PRIVADA);
		jCBTipoEmp.addItem(TipoEmpresa.PUBLICA);
	}

	private void refrescarComboSectorLab() {
		try {
			List<SectorLaboral> sectores = controlador.listaSectores();
			jCBSectorLab.removeAllItems();
			jCBSectorLab.addItem("Seleccione Opci�n");
			for (SectorLaboral sectorLaboral : sectores) {
				jCBSectorLab.addItem(sectorLaboral);
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private void refresacarComboEmpresas() {
		try {
			List<Empresa> lista = controlador.listaEmpresas();
			jCBEmpresaEgre.removeAllItems();
			jCBEmpresaEgre.addItem("Seleccione opci�n");
			for (Empresa empresa : lista) {
				jCBEmpresaEgre.addItem(empresa);
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	public class jpColor extends javax.swing.JPanel {

		private Color color1 = Color.BLACK;
		private Color color2 = Color.WHITE;

		public jpColor() {
		}

		public jpColor(Color c1, Color c2) {
			color1 = c1;
			color2 = c2;
		}

		public void paint(Graphics g) {
			Graphics2D g2 = (Graphics2D) g.create();
			Rectangle clip = g2.getClipBounds();
			g2.setPaint(new GradientPaint(0.0f, 0.0f, color1.darker(), 0.0f, getHeight(), color2.darker()));
			g2.fillRect(clip.x, clip.y, clip.width, clip.height);
		}

		public void setVistaColor() {
			this.color1 = new Color(66, 111, 166);
			this.color2 = new Color(103, 174, 118);
		}

	}

	private void pintarPanelRegistro() {
		Color c3 = Color.white;
		Color c4 = Color.green;
		jpColor jpmicolor1 = new jpColor(c3, c4);
		jpmicolor1.setSize(this.getSize());
		jPInfoPer.add(jpmicolor1);
		Color c5 = Color.white;
		Color c6 = Color.green;
		jpColor jpmicolor2 = new jpColor(c5, c6);
		jpmicolor2.setSize(this.getSize());
		jPInfoAcademica.add(jpmicolor2);
		Color c7 = Color.white;
		Color c8 = Color.green;
		jpColor jpmicolor3 = new jpColor(c7, c8);
		jpmicolor3.setSize(this.getSize());
		jPInfoLaboral.add(jpmicolor3);
		Color c9 = Color.white;
		Color c10 = Color.green;
		jpColor jpmicolor4 = new jpColor(c9, c10);
		jpmicolor4.setSize(this.getSize());
		jPOpciones.add(jpmicolor4);
	}

	private void pintarPanelPrincipal() {
		Color c1 = Color.green;
		Color c2 = Color.BLACK;
		jpColor jpmicolor = new jpColor(c1, c2);
		jpmicolor.setSize(this.getSize());
		jPPrinci.add(jpmicolor);
	}

}
